Populates both tables succesffully now
After deleting tables from render.com's database, you have to wait a few moments before you can make the new tables again otherwise you get this error:

sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "country" does not exist
LINE 1: INSERT INTO country (name, cca3, currency_code, currency, ca...